config/routes.rb
Rails.application.routes.draw do
  
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  root 'home#top'
  get 'home/about'

  get '/search', to: 'search#search'
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}

  validates :postal_code, presence: true
  validates :prefecture_code, presence: true
  validates :city, presence: true
  validates :street, presence: true

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    # ここでUser.new（と同等の操作）を行う
    build_resource(sign_up_params)

    # ここでUser.save（と同等の操作）を行う
    resource.save
    # ブロックが与えられたらresource(=User)を呼ぶ
    yield resource if block_given?
    if resource.persisted?
    # 先程のresource.saveが成功していたら
      if resource.active_for_authentication?
        # confirmable/lockableどちらかのactive_for_authentication?がtrueだったら
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        # リダイレクト先を指定
        respond_with resource, location: after_sign_up_path_for(resource)
        ThanksMailer.send_mail(current_user).deliver_now
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        # sessionを削除
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
    # 先程のresource.saveが失敗していたら
      # passwordとpassword_confirmationをnilにする
      clean_up_passwords resource
      # validatable有効時に、パスワードの最小値を設定する
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def follows
  end

  def followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.follower.count %></td>
      <td>フォロワー数：<%= user.followed.count %></td>
      <td>
        <% if current_user != user %>
          <% if current_user.following?(user) %>
            <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
          <% else %>
            <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
          <% end %>
        <% end %>
      </td>
      <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th>follows</th>
		<th><%= link_to user.follower.count, user_follows_path(user) %></th>
	</tr>
	<tr>
		<th>followers</th>
		<th><%= link_to user.followed.count, user_followers_path(user) %></th>
	</tr>
</table>
<!-- フォローボタン -->
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary"%>
  <% else %>
  <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class: "btn btn-success"%>
  <% end %>
<% end %>
<!-- フォローボタン -->
<% if current_user != user %>
  <%= link_to 'chatを始める', chat_path(user.id) %>
<% end %>
<% if user == current_user %>
  <div class="row">
	  <%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<%= render 'layouts/errors', obj: @user %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<%= render 'index', users: @users %>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<%= render 'books/index', books: @books %>
		<!--books一覧 -->
	</div>
</div>
<!-- 住所検索 -->
<% if @user == current_user %>
  <h2>Your Map</h2>
  <div id='map' class="<%= @user.prefecture_code + @user.city + @user.street %>"></div>
<% end %>
<style>
#map {
	height: 400px;
}
</style>
<script>
let map
let geocoder

function initMap(){
	geocoder = new google.maps.Geocoder()
	geocoder.geocode( {'address': $('#map').attr('class')}, function(results, status) { 
		if (status == 'OK') {
			map.setCenter(results[0].geometry.location);

			var marker = new google.maps.Marker({
				map: map,
				position: results[0].geometry.location
			});
		} else {
			alert('Geocode was not successful for the following reason: ' + status);
		}
	});

	map = new google.maps.Map(document.getElementById('map'), {
		center: {lat: -34.397, lng: 150.644},
		zoom: 8
	});
}

function codeAddress() {
	let inputAddress = document.getElementById('address').value;
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['SECRET_KEY'] %>&callback=initMap" async defer></script>
<!-- 住所検索 -->